version: '3'

services:
  postgresdev:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=caseyrharding
     - POSTGRES_DB=pgdev
  back-birthday:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8080:8080'
    working_dir: /back-birthday
    volumes:
      - ./back-birthday:/back-birthday
    depends_on:
      - postgresdev
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev