create table USERS (
    ID SERIAL,
    USERNAME varchar(100) NOT NULL UNIQUE,
    FIRST_NAME varchar(100),
    LAST_NAME varchar(100),
    EMAIL varchar(100),
    ABOUT_ME varchar(500),
    PASSWORD varchar(100),
    TIME_ADDED TIMESTAMP default CURRENT_TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

create table BIRTHDAYS (
    ID SERIAL,
    CREATOR integer,
    WANTED_GIFTS integer,
    ENDING TIMESTAMP default CURRENT_TIMESTAMP,
    TIME_ADDED TIMESTAMP default CURRENT_TIMESTAMP
    CONSTRAINT CREATOR FOREIGN KEY(CREATOR)
        REFERENCES USERS (ID)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT WANTED_GIFTS FOREIGN KEY(WANTED_GIFTS)
        REFERENCES GIFTS (ID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)

create table GIFTS (
    ID SERIAL,
    TITLE varchar(100),
    DESCRIPTION varchar(500),
    AMOUNT integer,
    CONTRAINT PK_GIFTS PRIMARY KEY (ID)
)